pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/sdk:9.0'
            args '-u root:root'
        }
    }

    environment {
        SOLUTION = "Source/RoomReservationSystem/RoomReservationSystem.sln"
        TEST_PATH = "Source/RoomReservationSystem/RoomReservationSystem.Tests"
        DOCKERFILE = "Source/RoomReservationSystem/RoomReservationSystem/Dockerfile"
        DOCKER_CONTEXT = "Source/RoomReservationSystem"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
                sh "ls -R"
            }
        }

        stage('Restore') {
            steps {
                sh "dotnet restore ${SOLUTION}"
            }
        }

        stage('Build') {
            steps {
                sh "dotnet build ${SOLUTION} -c Release --no-restore"
            }
        }

        stage('Tests') {
            steps {
                sh "dotnet test ${TEST_PATH} --no-build --logger trx"
            }
        }

        stage('Docker Build') {
            steps {
                sh """
                docker build -t roomreservationsystem:latest \
                    -f ${DOCKERFILE} \
                    ${DOCKER_CONTEXT}
                """
            }
        }
    }
}
