pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/sdk:9.0'
            args '-u root:root'
        }
    }

    environment {
        SOLUTION = "Source/RoomReservationSystem/RoomReservationSystem.sln"
        TEST_PATH = "Source/RoomReservationSystem/RoomReservationSystem.Tests"
        DOCKERFILE = "Source/RoomReservationSystem/RoomReservationSystem/Dockerfile"
        DOCKER_CONTEXT = "Source/RoomReservationSystem"
    }

    stages {


        stage('Restore') {
            steps {
				dir('Source/RoomReservationSystem')
					sh "dotnet restore ${SOLUTION}"
            }
        }

        stage('Build') {
            steps {
				dir('Source/RoomReservationSystem')
					sh "dotnet build ${SOLUTION} -c Release --no-restore"
            }
        }

        stage('Tests') {
            steps {
                sh "dotnet test ${TEST_PATH} --no-build --logger trx"
            }
        }

        stage('Docker Build') {
            steps {
				dir('Source/RoomReservationSystem')
					sh """
					docker build -t roomreservationsystem:latest \
						-f ${DOCKERFILE} \
						${DOCKER_CONTEXT}
					"""
            }
        }
    }
}
